Edit of Windows install + Linux reorganization
crate/crate-tutorials pull request #81
Opened 2022-07-05 18:44 UTC by matkuliak

## Summary of the changes / Why this is an improvement

Changes that we've agreed on with @proddata 
- Rename the "CrateDB and Linux" -> "Self-hosted CrateDB" which will host installs for various systems
- Remove the Windows mentions from [Ad-hoc install](https://crate.io/docs/crate/tutorials/en/latest/basic/index.html#ad-hoc-unix-macos-windows) and move it to mentioned "Self-hosted CrateDB"
    - Initial task asked for some screenshots, I don't think they're necessary here, opinions? 

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2022-07-06 11:05 UTC, proddata reviewed
In general looks good.
I think this might need some redirects on the server side

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +    CrateDB versions before 4.2 required a separate Java installation. For
I think we can remove the 4.2 notice by now, as it has been released 2 years ago and isn't really supported anymore. @amotl what do you think?

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +#. Download the latest `CrateDB release`_ from our Windows archive.
```suggestion
#. Download the latest `CrateDB release archive`_ for Windows.
```

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +.. _CrateDB release: https://cdn.crate.io/downloads/releases/cratedb/x64_windows/
```suggestion
.. _CrateDB release archive: https://cdn.crate.io/downloads/releases/cratedb/x64_windows/
```

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +Microsoft Windows
```suggestion
Windows
```

Maybe just Windows?

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +install CrateDB.
```suggestion
This section of the documentation outlines how to use the release archives to
run CrateDB on Microsoft Windows.
```

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +Microsoft Windows
We don't mention Canonical  for Ubuntu either

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +install CrateDB.
in the running text I think it is fine

2022-07-06 11:05 UTC, proddata commented on docs/self-hosted/windows.rst
> +Notes about Microsoft Windows
Maybe move that to an admonition block?

2022-07-13 10:41 UTC, amotl commented on docs/self-hosted/windows.rst
> +    CrateDB versions before 4.2 required a separate Java installation. For
I think it is fine to remove the notice.

2022-07-13 10:52 UTC, amotl requested changes
Thank you, @matkuliak.

@proddata:

> I think this might need some redirects on the server side.

Essentially, we need a single redirect from `/linux/*` to `/self-hosted/*`. Right?

2022-07-13 10:52 UTC, amotl commented on docs/basic/index.rst
> +:ref:`Microsoft Windows <windows-install>` setup the configuration files are
```suggestion
:ref:`Microsoft Windows <windows-install>` setup, the configuration files are
```

2022-07-13 10:52 UTC, amotl commented on docs/self-hosted/windows.rst
> +=================
reStructuredText requires the headline armor to be aligned with the length of the section title.

```suggestion
=======
Windows
=======
```

2022-07-13 10:52 UTC, amotl commented on docs/self-hosted/windows.rst
> +.. _contact us: https://crate.io/contact/
We employ a convention to sort those references alphanumerically. Can I ask you to change their order accordingly?

2022-07-13 13:12 UTC, amotl approved these changes
Thank you. Note: Please don't merge/rebuild until the redirect is in place.

2022-07-13 16:09 UTC, amotl commented
The redirect is in place, so it is good to go.

2022-07-13 16:18 UTC, merged