Update kubernetes.rst
crate/crate-tutorials pull request #89
Opened 2022-11-15 09:35 UTC by karynzv

edited the CrateDB version mentioned here which was not uniform. Replaced all version references for 5.0.3

## Summary of the changes / Why this is an improvement
Previously the versions mentioned here were not uniform, some places said 3.0.5 others had 4.1.2. Replaced them all for 5.0.3.

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2022-11-15 10:13 UTC, seut commented
Good catch! Maybe use most recent v5.1.1 instead?

2022-11-23 15:27 UTC, amotl requested changes
Thank you Karyn. I've discovered a minor typo, can you address it?

2022-11-23 15:27 UTC, amotl commented on docs/containers/kubernetes/kubernetes.rst
> +            image: crate: 5.1.1
There is one space too much.
```suggestion
            image: crate:5.1.1
```

2022-11-24 10:42 UTC, amotl approved these changes
Thanks! 👍

2022-12-29 15:03 UTC, merged